version: '3.8'

services:
  sender:
    build:
      context: ./sender
    volumes:
      - ./sender/traffic_data.csv:/app/traffic_data.csv
    depends_on:
      - server

  server:
    build:
      context: ./server
    ports:
      - "5000:5000"

  frontend:
    build:
      context: ./frontend
    ports:
      - "8080:80"
    depends_on:
      - server